"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageTypeOffset = exports.ChatType = void 0;
var ChatType;
(function (ChatType) {
    ChatType[ChatType["Unknown"] = -1] = "Unknown";
    ChatType[ChatType["Feed"] = 0] = "Feed";
    ChatType[ChatType["Text"] = 1] = "Text";
    ChatType[ChatType["Photo"] = 2] = "Photo";
    ChatType[ChatType["Video"] = 3] = "Video";
    ChatType[ChatType["Contact"] = 4] = "Contact";
    ChatType[ChatType["Audio"] = 5] = "Audio";
    ChatType[ChatType["DitemEmoticon"] = 6] = "DitemEmoticon";
    ChatType[ChatType["DitemGift"] = 7] = "DitemGift";
    ChatType[ChatType["DitemImg"] = 8] = "DitemImg";
    ChatType[ChatType["KakaoLinkV1"] = 9] = "KakaoLinkV1";
    ChatType[ChatType["Avatar"] = 11] = "Avatar";
    ChatType[ChatType["Sticker"] = 12] = "Sticker";
    ChatType[ChatType["Schedule"] = 13] = "Schedule";
    ChatType[ChatType["Vote"] = 14] = "Vote";
    ChatType[ChatType["Lottery"] = 15] = "Lottery";
    ChatType[ChatType["Map"] = 16] = "Map";
    ChatType[ChatType["Profile"] = 17] = "Profile";
    ChatType[ChatType["File"] = 18] = "File";
    ChatType[ChatType["StickerAni"] = 20] = "StickerAni";
    ChatType[ChatType["Nudge"] = 21] = "Nudge";
    ChatType[ChatType["Actioncon"] = 22] = "Actioncon";
    ChatType[ChatType["Search"] = 23] = "Search";
    ChatType[ChatType["Reply"] = 26] = "Reply";
    ChatType[ChatType["MultiPhoto"] = 27] = "MultiPhoto";
    ChatType[ChatType["Mvoip"] = 51] = "Mvoip";
    ChatType[ChatType["Custom"] = 71] = "Custom";
    ChatType[ChatType["PlusFriend"] = 81] = "PlusFriend";
    ChatType[ChatType["PlusFriendViral"] = 83] = "PlusFriendViral";
    ChatType[ChatType["Template"] = 90] = "Template";
    ChatType[ChatType["ApiTemplate"] = 91] = "ApiTemplate";
})(ChatType = exports.ChatType || (exports.ChatType = {}));
var MessageTypeOffset;
(function (MessageTypeOffset) {
    MessageTypeOffset.DELETED_MESSAGE_OFFSET = 16384;
})(MessageTypeOffset = exports.MessageTypeOffset || (exports.MessageTypeOffset = {}));
//# sourceMappingURL=chat-type.js.map